### ISSUE TITLE
�SyncFromMU Causing error in powershell

### ISSUE THREAD

**Issue by akilunovclq** [aws-quickstart/quickstart-microsoft-wsus#23]
https://github.com/aws-quickstart/quickstart-microsoft-wsus/blob/73a09520c1cb049bb8f7ce3d6ee07c159e897051/scripts/configure-wsus.ps1#L31

Wanted to bring this to your attention - there is a wrongly coded character in front of "SyncFromMU" which causes the script to fail. I'm guessing you meant to have a dash "-" but somewhere the encoding went wrong?

**Comment by davmayd** [comment]
Thank you for catching this, I will replace with the correct character
